wandb_version: 1

bootstrap:
  desc: null
  value: true
ccp_alpha:
  desc: null
  value: 0.0
class_weight:
  desc: null
  value: null
criterion:
  desc: null
  value: gini
max_depth:
  desc: null
  value: null
max_features:
  desc: null
  value: sqrt
max_leaf_nodes:
  desc: null
  value: null
max_samples:
  desc: null
  value: null
min_impurity_decrease:
  desc: null
  value: 0.0
min_samples_leaf:
  desc: null
  value: 1
min_samples_split:
  desc: null
  value: 2
min_weight_fraction_leaf:
  desc: null
  value: 0.0
monotonic_cst:
  desc: null
  value: null
n_estimators:
  desc: null
  value: 100
n_jobs:
  desc: null
  value: null
oob_score:
  desc: null
  value: false
random_state:
  desc: null
  value: null
verbose:
  desc: null
  value: 0
warm_start:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1707352632.087926
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.16.3
      8:
      - 5
      10:
      - 5
      13: linux-x86_64
    viz:
      class_proportions:
        id: wandb/class_proportions/v1
        historyFieldSettings:
          x-axis: _step
          key: class_proportions
      learning_curve:
        id: wandb/learning_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: learning_curve
      roc:
        id: wandb/roc/v1
        historyFieldSettings:
          x-axis: _step
          key: roc
      precision_recall:
        id: wandb/pr_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: precision_recall
      feature_importances:
        id: wandb/feature_importances/v1
        historyFieldSettings:
          x-axis: _step
          key: feature_importances
test_size:
  desc: null
  value: 0.2
train_len:
  desc: null
  value: 455
test_len:
  desc: null
  value: 114
